### ISSUE TITLE
CUDA out of memory error when validating using VAELM

### ISSUE THREAD

**Issue by saikrishnarallabandi** [saikrishnarallabandi/compositionality-expts#3]
Traceback (most recent call last):
 File "main_VAE.py", line 245, in <module>
   val_loss = evaluate(val_data)
 File "main_VAE.py", line 153, in evaluate
   recon_batch, mu, log_var = model(data, None)
 File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
   result = self.forward(*input, **kwargs)
 File "/home/srallaba/project_777/explorations/lm/model.py", line 45, in forward
   mu, log_var = self.encoder(embedding,hidden)
 File "/home/srallaba/project_777/explorations/lm/model.py", line 29, in encoder
   output, hidden = self.rnn(emb, hidden)
 File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
   result = self.forward(*input, **kwargs)
 File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 192, in forward
   output, hidden = func(input, self.all_weights, hx, batch_sizes)
 File "/usr/local/lib/python3.5/dist-packages/torch/nn/_functions/rnn.py", line 324, in forward
   return func(input, *fargs, **fkwargs)
 File "/usr/local/lib/python3.5/dist-packages/torch/nn/_functions/rnn.py", line 288, in forward
   dropout_ts)
RuntimeError: CUDA error: out of memory

**Comment by saikrishnarallabandi** [comment]
run with torch.no_grad()
